version: '3'
services:
  jupyter:
    build: .
    volumes:
      - './src:/project/src'
      - './src/lib:/project/notebook/lib'
      - './img:/project/img'
      - './notebook:/project/notebook'
      - './data:/project/data'
    ports:
      - '8888'
    env_file:
      - './jupyter.env'
